ccdn_component_common_moderator_cpanel:
    pattern: /{_locale}/dashboard/moderator
    defaults: { _controller: CCDNComponentDashboardBundle:Dashboard:show, _locale: en, category: moderator }

ccdn_component_common_admin_cpanel:
    pattern: /{_locale}/dashboard/admin
    defaults: { _controller: CCDNComponentDashboardBundle:Dashboard:show, _locale: en, category: admin }
