parameters:
    
    ccdn_component_common.component.helper.role.class:                          CCDNComponent\CommonBundle\Component\Helper\RoleHelper
    ccdn_component_common.component.helper.bin_si_units.class:                  CCDNComponent\CommonBundle\Component\Helper\BinSIUnits

    ccdn_component_common.component.twig_extension.bin.si.units.class:          CCDNComponent\CommonBundle\Component\TwigExtension\BinSIUnitsExtension
    ccdn_component_common.component.twig_extension.cycler.class:                CCDNComponent\CommonBundle\Component\TwigExtension\CyclerExtension
    ccdn_component_common.component.twig_extension.div_ceil.class:              CCDNComponent\CommonBundle\Component\TwigExtension\DivCeilExtension
    ccdn_component_common.component.twig_extension.trunc_dot.class:             CCDNComponent\CommonBundle\Component\TwigExtension\TruncDotExtension
    ccdn_component_common.component.twig_extension.relevant_date_format.class:  CCDNComponent\CommonBundle\Component\TwigExtension\RelevantDateFormatExtension
    ccdn_component_common.component.twig_extension.alert_key.class:             CCDNComponent\CommonBundle\Component\TwigExtension\AlertKeyExtension
    ccdn_component_common.component.twig_extension.user_role.class:             CCDNComponent\CommonBundle\Component\TwigExtension\UserRoleExtension
    ccdn_component_common.component.twig_extension.has_role.class:              CCDNComponent\CommonBundle\Component\TwigExtension\HasRoleExtension
    ccdn_component_common.component.twig_extension.abbr_number.class:           CCDNComponent\CommonBundle\Component\TwigExtension\AbbrNumberExtension
    ccdn_component_common.component.twig_extension.create_profile.class:        CCDNComponent\CommonBundle\Component\TwigExtension\CreateProfileExtension

    ccdn_component_common.pagerfanta.view.pagerfanta.class:                     CCDNComponent\CommonBundle\Component\Pagerfanta\View\TwitterBootstrapView
    ccdn_component_common.pagerfanta.view.pagerfanta_translated.class:          CCDNComponent\CommonBundle\Component\Pagerfanta\View\TwitterBootstrapTranslatedView
    
    ccdn_component_common.component.menu_builder.menu.class:                    CCDNComponent\CommonBundle\Component\MenuBuilder\Menu

services:

    #
    # Components.
    #
    ccdn_component_common.component.helper.bin_si_units:
        class: %ccdn_component_common.component.helper.bin_si_units.class%

    ccdn_component_common.component.helper.role:
        class: %ccdn_component_common.component.helper.role.class%
        arguments: [@service_container]

    #
    # Twig Extensions.
    #
    ccdn_component_common.component.twig_extension.binSIUnits:
        class: %ccdn_component_common.component.twig_extension.bin.si.units.class%
        arguments: [@ccdn_component_common.component.helper.bin_si_units]
        tags:
            - { name: twig.extension }
    ccdn_component_common.component.twig_extension.cycler:
        class: %ccdn_component_common.component.twig_extension.cycler.class%
        tags:
            - { name: twig.extension }
    ccdn_component_common.component.twig_extension.div_ceil:
        class: %ccdn_component_common.component.twig_extension.div_ceil.class%
        tags:
            - { name: twig.extension }
    ccdn_component_common.component.twig_extension.trunc_dot:
        class: %ccdn_component_common.component.twig_extension.trunc_dot.class%
        tags:
            - { name: twig.extension }
    ccdn_component_common.component.twig_extension.relevant_date_format:
        class: %ccdn_component_common.component.twig_extension.relevant_date_format.class%
        tags:
            - { name: twig.extension }
    ccdn_component_common.component.twig_extension.alert_key:
        class: %ccdn_component_common.component.twig_extension.alert_key.class%
        arguments: [@translator]
        tags:
            - { name: twig.extension }
    ccdn_component_common.component.twig_extension.user_role:
        class: %ccdn_component_common.component.twig_extension.user_role.class%
        arguments: [@ccdn_component_common.component.helper.role]
        tags:
            - { name: twig.extension }
    ccdn_component_common.component.twig_extension.has_role:
        class: %ccdn_component_common.component.twig_extension.has_role.class%
        arguments: [@ccdn_component_common.component.helper.role]
        tags:
            - { name: twig.extension }
    ccdn_component_common.component.twig_extension.abbr_number:
        class: %ccdn_component_common.component.twig_extension.abbr_number.class%
        tags:
           - { name: twig.extension }
    ccdn_component_common.component.twig_extension.create_profile:
        class: %ccdn_component_common.component.twig_extension.create_profile.class%
        arguments: [@ccdn_component_common.component.provider.profile]
        tags:
           - { name: twig.extension }

    #
    # Providers.
    #
    ccdn_component_common.component.provider.profile:
        class: %ccdn_component_common.component.provider.profile.class%
        arguments: [@service_container]
    ccdn_component_common.component.provider.user_provider:
        class: %ccdn_component_common.component.provider.user.class%
        arguments:
            - @doctrine
    #
    # Pagerfanta Views.
    #         
    ccdn_component_common.pagerfanta.view.pagerfanta:
        class: %ccdn_component_common.pagerfanta.view.pagerfanta.class%
        public: false
        tags:
            - { name: pagerfanta.view, alias: twitter_bootstrap_compact }
    #ccdn_component_common.pagerfanta.view.pagerfanta_translated:
    #    class: %ccdn_component_common.pagerfanta.view.pagerfanta_translated.class%
    #    arguments: [@pagerfanta.view.twitter_bootstrap, @translator]
    #    public: false
    #    tags:
    #        - { name: pagerfanta.view, alias: twitter_bootstrap_compact_translated }


    #
    # Menu Builder.
    #
    ccdn_component_common.component.menu_builder.menu:
        class: %ccdn_component_common.component.menu_builder.menu.class%
        tags:
            - { name: ccdn_component_menu.menu_builder }    
        