parameters:

    # Service Parameters defined in app/config

services:

    #
    # Components.
    #
    ccdn_component_common.component.helper.bin_si_units:
        class: %ccdn_component_common.component.helper.bin_si_units.class%

    ccdn_component_common.component.helper.role:
        class: %ccdn_component_common.component.helper.role.class%
        arguments: [@service_container]

    #
    # Twig Extensions.
    #
    ccdn_component_common.component.twig_extension.bin_si_units:
        class: %ccdn_component_common.component.twig_extension.bin_si_units.class%
        arguments:
            - @ccdn_component_common.component.helper.bin_si_units
        tags:
            - { name: twig.extension }

    ccdn_component_common.component.twig_extension.div_ceil:
        class: %ccdn_component_common.component.twig_extension.div_ceil.class%
        tags:
            - { name: twig.extension }

    ccdn_component_common.component.twig_extension.abbr_number:
        class: %ccdn_component_common.component.twig_extension.abbr_number.class%
        tags:
            - { name: twig.extension }
