parameters:

    ccdn_component_common.role_helper.class:                            CCDNComponent\CommonBundle\Component\Helper\RoleHelper
    ccdn_component_common.bin.si.units.class:                           CCDNComponent\CommonBundle\Component\BinSIUnits

    ccdn_component_common.bin.si.units.extension.class:                 CCDNComponent\CommonBundle\Extension\BinSIUnitsExtension
    ccdn_component_common.cycler.extension.class:                       CCDNComponent\CommonBundle\Extension\CyclerExtension
    ccdn_component_common.div_ceil.extension.class:                     CCDNComponent\CommonBundle\Extension\DivCeilExtension
    ccdn_component_common.param.extension.class:                        CCDNComponent\CommonBundle\Extension\ParamExtension
    ccdn_component_common.trunc_dot.extension.class:                    CCDNComponent\CommonBundle\Extension\TruncDotExtension
    ccdn_component_common.relevant_date_format.extension.class:         CCDNComponent\CommonBundle\Extension\RelevantDateFormatExtension
    ccdn_component_common.alert_key.extension.class:                    CCDNComponent\CommonBundle\Extension\AlertKeyExtension
    ccdn_component_common.user_role.extension.class:                    CCDNComponent\CommonBundle\Extension\UserRoleExtension

    ccdn_component_common.pagerfanta.view.pagerfanta.class:              CCDNComponent\CommonBundle\Component\Pagerfanta\View\TwitterBootstrapView
    ccdn_component_common.pagerfanta.view.pagerfanta_translated.class:   CCDNComponent\CommonBundle\Component\Pagerfanta\View\TwitterBootstrapTranslatedView
    
services:

    #
    # Components.
    #
    ccdn_component_common.bin.si.units:
        class: %ccdn_component_common.bin.si.units.class%

    ccdn_component_common.role_helper:
        class: %ccdn_component_common.role_helper.class%
        arguments: [@service_container]

    #
    # Twig Extensions.
    #
    ccdn_component_common.binSIUnits.extension:
        class: %ccdn_component_common.bin.si.units.extension.class%
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
    ccdn_component_common.cycler.extension:
        class: %ccdn_component_common.cycler.extension.class%
        tags:
            - { name: twig.extension }
    ccdn_component_common.param.extension:
        class: %ccdn_component_common.param.extension.class%
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
    ccdn_component_common.div_ceil.extension:
        class: %ccdn_component_common.div_ceil.extension.class%
        tags:
            - { name: twig.extension }
    ccdn_component_common.trunc_dot.extension:
        class: %ccdn_component_common.trunc_dot.extension.class%
        tags:
            - { name: twig.extension }
    ccdn_component_common.relevant_date_format.extension:
        class: %ccdn_component_common.relevant_date_format.extension.class%
        tags:
            - { name: twig.extension }
    ccdn_component_common.alert_key.extension:
        class: %ccdn_component_common.alert_key.extension.class%
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
    ccdn_component_common.user_role.extension:
        class: %ccdn_component_common.user_role.extension.class%
        arguments: [@ccdn_component_common.role_helper]
        tags:
            - { name: twig.extension }

    #
    # Pagerfanta Views.
    #
            
    ccdn_component_common.pagerfanta.view.pagerfanta:
        class: %ccdn_component_common.pagerfanta.view.pagerfanta.class%
        public: false
        tags:
            - { name: pagerfanta.view, alias: twitter_bootstrap_compact }
    #ccdn_component_common.pagerfanta.view.pagerfanta_translated:
    #    class: %ccdn_component_common.pagerfanta.view.pagerfanta_translated.class%
    #    arguments: [@pagerfanta.view.twitter_bootstrap, @translator]
    #    public: false
    #    tags:
    #        - { name: pagerfanta.view, alias: twitter_bootstrap_compact_translated }

        
        